package org.example.quizzappbackend.enums;

public enum Category {
    GENERAL_KNOWLEDGE,
    ENTERTAINMENT_BOOKS,
    ENTERTAINMENT_FILM,
    ENTERTAINMENT_MUSIC,
    ENTERTAINMENT_MUSICALS_THEATRES,
    ENTERTAINMENT_TELEVISION,
    ENTERTAINMENT_VIDEOGAMES,
    ENTERTAINMENT_BOARDGAMES,
    SCIENCE_NATURE,
    SCIENCE_COMPUTERS,
    SCIENCE_MATHEMATICS,
    MYTHOLOGY,
    SPORTS,
    GEOGRAPHY,
    HISTORY,
    POLITICS,
    ART,
    CELEBRITIES,
    ANIMALS
}
