package org.example.quizzappbackend.enumeration;

public enum Category {
    ANIMALS,
    ART,
    CELEBRITIES,
    ENTERTAINMENT_BOARD_GAMES,
    ENTERTAINMENT_BOOKS,
    ENTERTAINMENT_COMICS,
    ENTERTAINMENT_CARTOON_ANIMATIONS,
    ENTERTAINMENT_FILM,
    ENTERTAINMENT_JAPANESE_ANIME_MANGA,
    ENTERTAINMENT_MUSIC,
    ENTERTAINMENT_MUSICALS_THEATRES,
    ENTERTAINMENT_TELEVISION,
    ENTERTAINMENT_VIDEO_GAMES,
    GENERAL_KNOWLEDGE,
    GEOGRAPHY,
    HISTORY,
    MYTHOLOGY,
    POLITICS,
    SCIENCE_COMPUTERS,
    SCIENCE_GADGETS,
    SCIENCES_MATHEMATICS,
    SCIENCE_NATURE,
    SPORTS,
    VEHICLES
}
